WIP add details to pnl transaction and fees tests
Drakkar-Software/OctoBot-Trading pull request #685
Opened 2022-01-29 16:36 UTC by GuillaumeDSM

2022-01-30 17:27 UTC, Herklos reviewed
nice :+1:

2022-01-30 17:27 UTC, Herklos commented on octobot_trading/personal_data/exchange_personal_data.py
> +                await position.update(update_margin=-position.value * funding_rate)
:+1:

2022-01-30 17:27 UTC, Herklos commented on octobot_trading/personal_data/positions/position.py
> +        self.first_entry_time = 0
Why not using `creation_time` and set `creation_time` at first entry instead of object creation time? Because `creation_time` is useless for now

2022-01-30 17:27 UTC, Herklos commented on octobot_trading/personal_data/positions/position.py
> +            self.already_reduced_size += size_update
Can you create a method for this please? Something like `_update_exit_price(on_liquidation=True)`

2022-01-30 17:27 UTC, Herklos commented on octobot_trading/personal_data/positions/position.py
> +            self.already_reduced_size += size_update
A there we should have something like `_update_exit_price(size_update, on_liquidation=False)` (previous comment)

2022-01-30 17:27 UTC, Herklos commented on octobot_trading/personal_data/positions/position.py
> +                self.first_entry_time = self.exchange_manager.exchange.get_exchange_current_time()
```suggestion
                self.creation_time = self.exchange_manager.exchange.get_exchange_current_time()
```
(linked to a previous comment)

2022-01-30 17:27 UTC, Herklos commented on octobot_trading/personal_data/positions/position.py
> +                logging.get_logger(self.get_logger_name()).info(f"Changed position side: now {self.side.name}")
I think it should be clearer with a method to handle this event like `on_side_update`

2022-01-30 17:27 UTC, Herklos commented on octobot_trading/personal_data/positions/position.py
> +            self.update_average_exit_price(size_update, self.mark_price)
I think we should catch `InvalidOperation` and probably `DivisionByZero` here. We should put this in a method (linked to other comments)

2022-01-30 17:27 UTC, Herklos commented on octobot_trading/personal_data/positions/types/linear_position.py
> +        total_contract_value = self.already_reduced_size + update_size
:+1:

2022-01-30 17:27 UTC, Herklos commented on octobot_trading/personal_data/positions/types/linear_position.py
> +    def update_average_exit_price(self, update_size, update_price):
Can you also add this method implementation for `inverse_position` please?

2022-01-30 17:27 UTC, Herklos commented on tests/personal_data/positions/types/test_linear_position.py
> +def check_created_transaction(exchange_manager, closed_quantity, cumulated_closed_quantity):
:+1:

2022-01-30 17:27 UTC, Herklos commented on octobot_trading/personal_data/positions/position.py
> +    def _update_realized_pnl_from_size_update(self, size_update, is_closing=False, order_price=constants.ZERO):
I would prefer that we call it `update_price` instead of `order_price`

2022-02-03 15:09 UTC, Herklos requested changes
Awesome work on tests and tests documentation :100:

2022-02-03 15:09 UTC, Herklos commented on tests/personal_data/portfolios/types/test_future_portfolio.py
> +    profits = (sell_order_price - buy_order_price) * max_buy_quantity * 2
:+1:

2022-02-03 15:09 UTC, Herklos commented on tests/personal_data/portfolios/types/test_future_portfolio.py
> +    # warning here: due to issues on decimal.Decimal precision (22+th digit, no impact), keep real order in operations
:open_mouth: :open_mouth:

2022-02-03 15:09 UTC, Herklos commented on tests/personal_data/portfolios/types/test_future_portfolio.py
> -    if os.getenv('CYTHON_IGNORE'):
:+1:

2022-02-03 15:09 UTC, Herklos commented on tests/personal_data/portfolios/types/test_future_portfolio.py
> +    # data from real test on Bybit from 02.02.2020 using 2 market orders:
:+1:

2022-02-03 15:09 UTC, Herklos commented on tests/personal_data/portfolios/types/test_future_portfolio.py
> +    fees_per_order = decimal.Decimal('0.2887')
```suggestion
    fees_per_order = decimal.Decimal('0.2887')  # 0.2887 = 0.5775 / 2
```

2022-02-03 15:09 UTC, Herklos commented on tests/personal_data/portfolios/types/test_future_portfolio.py
> +    # data from real test on Bybit from 02.02.2020 using 2 market orders:
I really like this way of creating a test

2022-02-03 15:09 UTC, Herklos commented on tests/personal_data/portfolios/types/test_future_portfolio.py
> +            assert position.realised_pnl == total_pnl
:100:

2022-02-03 16:11 UTC, GuillaumeDSM commented on octobot_trading/personal_data/positions/position.py
> +                update_price=self.mark_price, already_counted_realised_pnl_update=realised_pnl_update)
No reason, you are right !

2022-02-03 17:53 UTC, Herklos approved these changes
Really nice work :+1:

2022-02-03 18:30 UTC, merged